[package]
name = "tenpin"
version = "0.1.0"
authors = ["Dean Bassett <dean@deanveloper.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
